name: CI
on: [push, pull_request]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install requirements (python)
      run: pip3 install pytest

    - name: Setup up PYTHONPATH
      run: echo "PYTHONPATH=${PWD}/src" >> $GITHUB_ENV

    - name: Run regression tests
      run: python3 -m pytest