name: CI
on: [push, pull_request]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install requirements
      run: |
        pip install --upgrade pip
        pip3 install pytest

    - name: Install project
      run: pip3 install .

    - name: Check for broken requirements
      run: pip3 check

    - name: Run regression tests
      run: python3 -m pytest